### ISSUE TITLE
m_n_supercell_new.py

### ISSUE THREAD

**Issue by cty07** [lxf-gzu/vasp_small_script#1]
By XueFei Liu
The lattice constant for structure a:3.273
The lattice constant for structure b:2.556
***The possible new constants***

Sqrt(lat_a): [5.0001, 9.9999, 9.9999, 7.9999, 13.0001, 20.0, 18.0001]
Sqrt(lat_b): [8.0001, 17.0001, 18.0, 13.0, 20.0001, 31.9999, 31.9999]

Produce m n groups for structure a...
Traceback (most recent call last):
  File "m_n_supercell_new.py", line 112, in <module>
    theta=(30/360)*np.pi*2)
  File "m_n_supercell_new.py", line 33, in m_n
    c_1=round(ab2b1/(b1_v*ab2_v),4)
ZeroDivisionError: float division by zero

**Comment by 123bxb** [comment]
I have the same problem. Have you solved it yet?
